// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXkdRaK1Rp8FNEy1X_K7g_qxSfjDPJ1Ds',
    appId: '1:1004513750843:web:df7a5e54659367a867911e',
    messagingSenderId: '1004513750843',
    projectId: 'flutter-app-7dc41',
    authDomain: 'flutter-app-7dc41.firebaseapp.com',
    storageBucket: 'flutter-app-7dc41.firebasestorage.app',
    measurementId: 'G-01DWY8419R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiqpz9tv-UrZNgurEuYmtXLHt23GQV940',
    appId: '1:1004513750843:android:54845a1b101ebc6b67911e',
    messagingSenderId: '1004513750843',
    projectId: 'flutter-app-7dc41',
    storageBucket: 'flutter-app-7dc41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb8hQy2SuC224IpHkOtPoUfxVT1il7vGA',
    appId: '1:1004513750843:ios:38817c45de8b040967911e',
    messagingSenderId: '1004513750843',
    projectId: 'flutter-app-7dc41',
    storageBucket: 'flutter-app-7dc41.firebasestorage.app',
    iosBundleId: 'com.example.flutterImage',
  );
}
